#só vai disparar se tiver uma alteração no source

name: Workflow Evento
on:
  push:
    branches: ["main", "features/*"]
    paths:
      - "src/**"
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de Teste
        run: echo "Action executada apenas em maintenence"
