name: Workflow Evento
on:
  push:
    branches: ["main", "features/*"]
    tags:
      - v*
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de Teste
        run: echo "Action executada apenas em main teste 200000"
